In [1]:
from pandas import read_csv
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score

In [2]:
pt_trig=read_csv('pt_trigram_count.tsv',sep='\t');
en_trig=read_csv('en_trigram_count.tsv',sep='\t');
es_trig=read_csv('es_trigram_count.tsv',sep='\t');
fr_trig=read_csv('fr_trigram_count.tsv',sep='\t');

In [3]:
print("PT shape:", pt_trig.shape, "EN shape:", en_trig.shape, "ES shape:", es_trig.shape, "FR shape:", fr_trig.shape)
print("PT shape:\n", pt_trig.head(), "\nEN shape:\n", en_trig.head(), "\nES shape:\n", es_trig.head(), "\nFR shape:\n", fr_trig.head())

PT shape: (41556, 3) EN shape: (41556, 3) ES shape: (41556, 3) FR shape: (41556, 3)
PT shape:
    0  ñpq   0.1
0  1  asf  6401
1  2  äíá     0
2  3  yüa     0
3  4  nkô     0
4  5  äíé     0 
EN shape:
    0  ñpq   1
0  1  asf  60
1  2  äíá   8
2  3  yüa   1
3  4  nkô   1
4  5  äíé   2 
ES shape:
    0  ñpq    0.1
0  1  asf  17257
1  2  äíá      0
2  3  yüa      0
3  4  nkô      0
4  5  äíé      0 
FR shape:
    0  ñpq   0.1
0  1  asf  5469
1  2  äíá     0
2  3  yüa     0
3  4  nkô     0
4  5  äíé     0


In [4]:
PT=pt_trig.to_numpy()
EN=en_trig.to_numpy()
ES=es_trig.to_numpy()
FR=fr_trig.to_numpy()
X_train=np.zeros((4,PT.shape[0]))
X_train[0]=PT[:,2].transpose()
X_train[1]=EN[:,2].transpose()
X_train[2]=ES[:,2].transpose()
X_train[3]=FR[:,2].transpose()
y_train=np.arange(4)


In [5]:
model = MultinomialNB(alpha=1,fit_prior=False)
model.fit(X_train,y_train)

MultinomialNB(alpha=1, fit_prior=False)

In [ ]:
#perguntar a stora se e para fazer o meu proprio teste
y_prediction=model.predict(x=X_test)
print("Accuracy score:", accuracy_score(y_test, y_prediction))

In [6]:
sentences=np.array(['Que fácil es comer peras.',
                    'Que fácil é comer peras.',
                   'Today is a great day for sightseeing.',
                   'Je vais au cinéma demain soir.',
                   'Ana es inteligente y simpática.',
                   'Tu vais à escola hoje.'],dtype=object)

In [7]:
vectorizer = CountVectorizer(vocabulary=PT[:,1],analyzer='char',ngram_range=(3, 3))
X_test=vectorizer.fit_transform(sentences)
y_test=np.array([2,0,1,3,2,0])

In [8]:
y_prediction=model.predict(X_test.toarray())
print(y_prediction)
print("Accuracy score:", accuracy_score(y_test, y_prediction))

[2 0 1 3 2 3]
Accuracy score: 0.8333333333333334


In [9]:
prediction=model.predict_proba(X_test.toarray())
print(prediction)

[[3.29653329e-01 1.58939428e-14 6.70346664e-01 6.54820052e-09]
 [9.99995230e-01 1.74725563e-22 4.76969140e-06 2.94565266e-12]
 [4.34380848e-17 1.00000000e+00 4.76869531e-18 5.44818540e-20]
 [1.52370736e-11 6.10703382e-24 1.66309686e-15 1.00000000e+00]
 [2.87040890e-05 2.66357254e-17 9.99971296e-01 2.17429760e-13]
 [2.06949642e-01 5.21413728e-21 2.68686074e-08 7.93050332e-01]]


In [11]:
prediction=np.sort(prediction)
print(np.sort(prediction))

[[1.58939428e-14 6.54820052e-09 3.29653329e-01 6.70346664e-01]
 [1.74725563e-22 2.94565266e-12 4.76969140e-06 9.99995230e-01]
 [5.44818540e-20 4.76869531e-18 4.34380848e-17 1.00000000e+00]
 [6.10703382e-24 1.66309686e-15 1.52370736e-11 1.00000000e+00]
 [2.66357254e-17 2.17429760e-13 2.87040890e-05 9.99971296e-01]
 [5.21413728e-21 2.68686074e-08 2.06949642e-01 7.93050332e-01]]


In [12]:
class_margin=np.zeros((6,1))
for i in range(6):
    class_margin[i]=prediction[i,prediction.shape[1]-1]-prediction[i,prediction.shape[1]-2]
print(class_margin)

[[0.34069333]
 [0.99999046]
 [1.        ]
 [1.        ]
 [0.99994259]
 [0.58610069]]
