In [68]:
import numpy as np
import scipy as scipy
import matplotlib.pyplot as plt

In [23]:
data1_xtest = np.load("./data1_lab4/data1_xtest.npy")
data1_xtrain = np.load("./data1_lab4/data1_xtrain.npy")
data1_ytest = np.load("./data1_lab4/data1_ytest.npy")
data1_ytrain = np.load("./data1_lab4/data1_ytrain.npy")


In [109]:
classes, counts = np.unique(data1_ytrain, return_counts=True)
probs = counts / data1_ytrain.shape[0]


In [104]:
data_split = {}

for c in classes:
    data_split[c] = data1_xtrain[np.where(data1_ytrain == c)]
    

In [102]:
for c in data_split:
    print()
    print(c)
    print(data_split[c])


1.0
[ 1.0207727   2.76022827  3.82404138  2.47082292  1.29066983  0.27567162
 -0.95787715  2.06430037  2.4983044   0.93747874  0.78121688  1.81583909
  2.28788349 -0.24272235  1.75065147  1.57908821 -0.1395699   2.15639142
 -0.08539132  0.06994977  1.71467997  1.80432046  1.33052948  2.01333466
 -0.66571751  0.4768212  -3.29995022  2.817067    0.79514475  0.93387779
  3.24496761  1.8727464   0.86005675  0.42172007  1.16879626  2.15145651
 -0.23432724  1.83695281  3.41141754 -0.42943038  2.07900793  2.67840147
 -0.04601071 -0.94271883  1.60642513  2.13750217  2.52520608  2.85657055
 -0.27809667  2.52197229]

2.0
[-0.13445079 -0.31215832 -1.93170612 -1.24527898 -1.43444315 -1.99437738
 -2.34035183 -1.85489769 -1.68138035 -0.41254593 -0.84859216 -0.68701969
 -2.44685808 -1.39254088 -3.08087025 -1.6746334  -2.27847572 -0.55016322
 -1.28757292 -0.3228572  -2.46722166 -2.32926054 -3.34982371 -2.44317728
 -3.4563472  -1.41730535 -1.18054788 -1.90543824 -1.80289483 -1.18172804
 -0.29230632 -0

In [110]:
mean = np.mean(data1_xtrain, axis=0)
mean

array([0.29613618, 2.69475387])

In [111]:
var = np.var(data1_xtrain, axis=0)
var

array([3.27114398, 3.58723406])

In [112]:
# Takes single values
def p(x, mean, var):
    return (1 / np.sqrt(2 * np.pi * var)) * np.exp((-(x-mean)**2)/(2*var))


# Takes vectors
def posterior(X, mean, var):
    
    posterior = 0
    for i in range(len(X)):
        posterior *= p(X[i], mean[i], var[i])
        
    return posterior



In [113]:
p(1,1,1)

0.3989422804014327

In [72]:
from scipy import stats

In [78]:
vals = stats.norm.ppf([1, 1, 1])
vals

array([inf, inf, inf])